# Aici pui cheia organizației tale și a proiectului (le găsești pe SonarCloud)
sonar.organization=valentin222259
sonar.projectKey=Valentin222259_Space-Tourism

# Spunem unde este codul sursă
sonar.sources=src

# Ignorăm fișierele generate automat sau node_modules pentru a face scanarea mai rapidă
sonar.exclusions=node_modules/**, dist/**, public-build/**